/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rjoshi1' at '8/25/16 11:13 AM' with Gradle 2.13
 *
 * @author rjoshi1, @date 8/25/16 11:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
